# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7549878e1fdc31fa17510720596ba0f43fcad881e6d6ec0090a9a6eb66f6c367aa38fa91023e4353e0cb7dfa08d41e1381d15b9c4b4fdf7bccd82f91c4649c80

test:
  secret_key_base: 0a34e7f97a200e925a64a24e9cc4394662afc661436d8801836cf5cb6ee3fe4ccff64f5e69bc777a081fdbdcbaa1dba58c95ebd486a05ff98446630fd6c7b800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
